CREATE TABLE app_tokens (
	ID 					INT	 			NOT NULL AUTO_INCREMENT,
	TOKEN				VARCHAR(512) 	NOT NULL,
	USER_ID				INT			 	NOT NULL,
	LOCALE				VARCHAR(255)	NOT NULL DEFAULT 'ES',
	APP_VERSION			VARCHAR(255) 	NULL,
	OS					VARCHAR(255)	NULL,
	OS_VERSION			VARCHAR(255)	NULL,
	CREATION_DATE		TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_DATE			TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ACTIVE				BOOLEAN			NOT NULL DEFAULT TRUE,
	PRIMARY KEY (ID)
);


CREATE UNIQUE INDEX IDX_USER_TOKEN ON app_tokens (TOKEN,USER_ID);