CREATE TABLE subscribers (
	ID 					INT	 			NOT NULL AUTO_INCREMENT,
	USER_ID				INT			 	NOT NULL,
	DEVICE_ID			VARCHAR(255)	NOT NULL,
	PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_SUBSCRIBER ON subscribers (USER_ID,DEVICE_ID);